### ISSUE TITLE
Sporadic crashes when installing/removing/updating packages

### ISSUE THREAD

**Issue by mentaljam** [mentaljam/harbour-storeman#40]
https://openrepos.net/comment/23760#comment-23760

**Comment by Olf0** [comment]
BTW, I have not experienced this issue anymore, lately (maybe since Storeman 0.0.24 or so).

Although I am performing all actions purely sequentially (i.e. doing nothing while the repos are refreshed, doing nothing else while an application is installing etc.), older Storeman versions used to crash regularly for me when installing or removing apps.
Still I always found the corresponding app to be properly installed (or uninstalled) after such a crash.

**Comment by mentaljam** [comment]
Seems to be fixed

**Comment by Olf0** [comment]
Ack, as I continue **not** to experience "Crashes while installing or uninstalling software", even though I started using Storeman doing things in parallel (Refreshing repos, installing software, Reading / writing comments, etc.) with v0.0.26.
It is doing all that nicely: Thanks.
