### ISSUE TITLE
Date format not consistent

### ISSUE THREAD

**Issue by bitbooster** [mentaljam/harbour-storeman#51]
Issue with Storeman 0.0.22 (on Oneplus X w/ Sailfish 2.1.4.14, language set to English UK).

The format used for dates seem inconsistent. To make an example, with current version of Storeman:
- in the 'Recently updated' list, the date field is reported as "26/04/2018"
- however if you tap on the app, read the description and check at the bottom the Last Updated field, it is listed as "2018-26-04 22:25"
So one uses MM/DD/YYYY, the other YYYY/DD/MM, which may cause some confusion when e.g. reading of an app last updated on 2018-07-01 :)

**Comment by mentaljam** [comment]
To format dates in Storeman the methods of the [QML Date type](https://doc.qt.io/qt-5/qml-qtqml-date.html) are used:

- [toLocaleDateString](https://doc.qt.io/qt-5/qml-qtqml-date.html#toLocaleDateString-method) with the [NarrowFormat](https://doc.qt.io/qt-5/qlocale.html#FormatType-enum) is used for lists like "Recently updated" and search results (see [AppListDelegate.qml](https://github.com/mentaljam/harbour-storeman/blob/50fa68df8ab235dcd3d4e31c355b278302ad05a3/harbour-storeman/qml/components/AppListDelegate.qml#L88))
- [toLocaleString](https://doc.qt.io/qt-5/qml-qtqml-date.html#toLocaleString-method) with custom text format is used for the application page (see [AppInformation.qml](https://github.com/mentaljam/harbour-storeman/blob/50fa68df8ab235dcd3d4e31c355b278302ad05a3/harbour-storeman/qml/components/AppInformation.qml#L149))

Your issue is about the second method. By default the ISO date (YYYY-MM-DD) is used. To change it one should request a required language on [Transifex](https://www.transifex.com/mentaljam/harbour-storeman) then find and "translate" the string "yyyy-dd-MM hh:mm" according to [this reference](http://doc.qt.io/qt-5/qdate.html#toString).

I decided to use custom text format for the second method to give more options when localizing Storeman. For example QLocale::LongFormat and QLocale::ShortFormat use long and short month names for date but in Russia months are most often written in numeric form.

**Comment by Olf0** [comment]
@mentaljam, I stumbled across this usability issue a while ago and finally took the effort to report it, just to find it already filed by @bitbooster.
My system language is also set to *en_GB* (in SailfishOS' settings) and experience the same inconsistencies (though IMHO @bitbooster's description is slightly incoherent, hence I am trying to provide a comprehensive description below).

1. In the application details, the "Last updated" field displays the timestamp in the format YYYY-DD-MM HH:MM
    - I would call this date format "europeanised ISO-format" (i.e. month and day fields are swapped, compared to the real ISO-format). The 24 hour time format is fine, as it is "true ISO style".
    - So IMHO the original, untranslated date string here is already inconsistent (i.e. on its own).
2. In the "Recently updated" list, the timestamp for each application is in the format  DD/MM/YYYY
    - I would call this "European date format with English separators".
    - It is completely inconsistent to the other date format used in 1.

As the source language of Storeman's TS-files is plain *en*, I would expect plain (international) ISO date format YYYY-MM-DD to be used at all places in Storeman, i.e. ISO order of the sub-fields separated by dashes (and 24 hour time format, which is already the case).
Please adapt both date fields to the real ISO-format in the source language / TS-file.

P.S.: IMO creating *en_US*, *en_GB* and other *en_\** locales just for fixing this usability issue only further complicates the already convoluted topic of locales and date/time formats.
And IMHO the current behaviour appears to be simply wrong (which does not imply it is all Storeman's fault, Qt may also contribute to this), but I cannot see that your statement 
> By default the ISO date (YYYY-MM-DD) is used.

currently holds true anywhere in Storeman.

Tested with Storeman 0.0.26 under SFOS 2.1.4.14 on a Jolla 1 phone.

**Comment by mentaljam** [comment]
Ok, now I see it was a kind of typo. I was fully sure that the format is `YYYY-MM-DD`. I'll fix it in next releases. Thank you for pointing me once again :)

> As the source language of Storeman's TS-files is plain en, <...>

No it's not plain en. It's engineering (technical) English. I use ID-based translations specially for it. The source strings are loaded only if there are no translations for the current locale. In other words Storeman currently is not translated to English.

**Comment by Olf0** [comment]
> I'll fix it in next releases. 

Thanks!
But AFAICS, commit [b19b7c5](https://github.com/mentaljam/harbour-storeman/commit/b19b7c551c81a9c85e11745d77c49be2e18b2ccd) only fixes the [incorrect date format #1](https://github.com/mentaljam/harbour-storeman/issues/51#issuecomment-394090307), or am I missing something WRT #2 (und "Recently updated", being "dd/MM/yyyy").

> Thank you for pointing me once again :)

Seriously, bug reporting is the least I can do for supporting your truly valuable software.

> No it's not plain en. It's engineering (technical) English.

Perfect, that is exactly what I want (with real ISO date format everywhere ;) ).

And thanks for the technical explanation, which made me understand that *en* is what I want.
But if somebody contributes an *en_GB* TS-file in the future, how do I prevent it from being used in Storeman (in order to continue using *en*) while leaving the locale in SailfishOS on *en_GB* (as it lacks *en* or *en_DK*, which represents "international / continental European English")?

**Comment by mentaljam** [comment]
In lists like "Recently updated" and search results [NarrowFormat](https://doc.qt.io/qt-5/qlocale.html#FormatType-enum) is used. The resulting format depends on the current locale.

> <...>  how do I prevent it from being used in Storeman <...>

Currently there is no way to change language in Storeman. But you can remove qm files from `/usr/share/harbour-storeman/translations/`.

**Comment by Olf0** [comment]
> In lists like "Recently updated" and search results NarrowFormat is used.

Oh, 
* the quoted [Qt documentation](https://doc.qt.io/qt-5/qlocale.html#FormatType-enum) strongly suggests to "avoid using it for date formatting" and calls out two specific reasons.
* the date format @bitbooster and I both see being used in "Recently updated" (*dd/MM/yyyy*, i.e. solely numbers) is definitely not the [NarrowFormat](https://doc.qt.io/qt-5/qlocale.html#FormatType-enum), as it lacks a literal month.

> The resulting format depends on the current locale.

Oh, now we made the full circle. ;)
* @bitbooster and I use the system locale *en_GB* (set in SailfishOS' settings).
* Storeman currently lacks a TS-file for *en_GB*, thus the specific locale *en_GB* is not supported.
* Hence Storeman should fall back to its default locale *en* ("engineering English").
* For "engineering English" an (any) ISO-style date format shall be used.

But the format observed in "Recently updated" is *dd/MM/yyyy*, which
* does not use ISO separators, i.e. "-" instead of  currently "/".
* does not use ISO order (i.e. from the most significant part to the least significant one): *yyyy-MM-dd*
* hence is no ISO date format at all.

Thus my suggestions are:
* In "Recently updated" use either the numerical format (that would be my preference), as already in "Last updated" *and* in (at least for users of the system locales *en_\**) "Recently updated" (although in an incorrect format).  Or [ShortFormat](https://doc.qt.io/qt-5/qlocale.html#FormatType-enum), as that is what the Qt documentation suggests and as you originally intended to display a literal month (instead of a numerical one).
* The order of *all* date fields shall correspond to the used locale (i.e. system locale, if available in Storeman, otherwise its fallback *en*).
* The separators of *all* date fields shall correspond to the used locale (i.e. system locale, if available in Storeman, otherwise its fallback *en*).

**Comment by Olf0** [comment]
> Currently there is no way to change language in Storeman. But you can remove qm files from /usr/share/harbour-storeman/translations/.

That is absolutely O.K. for me, if *en* ("engineering English"), respectively the fallback to it, would be properly working in Storeman.

**Comment by mentaljam** [comment]
The app list delegate is not the only place where Qt locale formatting is used. It's also used for dates in comments and for numbers (compare en 1,000.00 and ru 1 000,00).

> Most important IMO is, that the date / time formats are consistent throughout Storeman for any selected system locale <...>

It's a very controversial statement. [Date formats differ a lot in different countries](https://en.wikipedia.org/wiki/Date_format_by_country).

I will add a fallback to a default locale if no translations were loaded.

**Comment by Olf0** [comment]
> It's a very controversial statement.

Oh, sorry.  No, it was not meant this way, but extremely easy to interpret so.

"Most important IMO is, that the date / time formats are consistent throughout Storeman for any specific system locale \<....\>" or just "\<...\> each system locale \<...\>" would have been more concise.
Anyway, it was just another way of saying, "Seeing both, *dd/MM/yyyy* and *yyyy-MM-dd* within Storeman 0.0.27 (both formats have swapped month and day subfields compared to v0.0.26 for me) is irritating users."

Thanks for your efforts, I am looking forward to v0.0.28.

**Comment by Olf0** [comment]
Retested with Storeman 0.0.30 under SFOS 2.2.1.18.
Still the same setup, i.e. 

    $ env | fgrep LANG
    LANG=en_GB.utf8
    $
1. In the application details, the timestamps are displayed in proper ISO format now:
![screenshot_20181120_002](https://user-images.githubusercontent.com/16547876/48803099-51f46c00-ed11-11e8-97b1-e291addbf009.png)
Thank you for commit b19b7c5 rectifying this!
2. Still the list of recently updated applications (i.e. Storeman's top-level view) displays proper, traditional British date format (checked against [Wikipedia, which provides a separate article on this](https://en.wikipedia.org/wiki/Date_and_time_notation_in_the_United_Kingdom)):
![screenshot_20181120_001](https://user-images.githubusercontent.com/16547876/48803084-4739d700-ed11-11e8-9781-17d4d2fd44cf.png)
The same applies to the list of bookmarks:
![screenshot_20181120_003](https://user-images.githubusercontent.com/16547876/48803121-59b41080-ed11-11e8-85b9-cb3c12951876.png)

So while both date formats are each O.K. and logical now, the inconsistency of using multiple, different date formats in Storeman remains, unfortunately.
Somehow the British English locale (en_GB) is still applied for formatting the dates in 2., above.  As I cannot find this date string in [translations/harbour-storeman.ts](https://github.com/mentaljam/harbour-storeman/blob/master/translations/harbour-storeman.ts), I assume they are generated by some QML code somewhere?

**Comment by Olf0** [comment]
Mmmh, while I never coded in QML / JavaScript, isn't a statement [like this](https://github.com/mentaljam/harbour-storeman/commit/17463ade648d79a06d9028c7e25aece71fe89dfe) implicitly using the system locale?

**Comment by Olf0** [comment]
Ah, I found the **long** literal date format being used for old comments, but that is a "count up" going from "XX minutes ago" over  "YY hours ago " to "Weekday, DD Month YYYY", which is nice.

Still I haven't found QT's **short** date format being used anywhere in Storeman.
