### ISSUE TITLE
Add a hint about using the rating overlay

### ISSUE THREAD

**Issue by mentaljam** [mentaljam/harbour-storeman#75]
Relates #74

**Comment by Olf0** [comment]
If you mean "exiting / leaving" by "using" in the issue title (you may want to change that), I fully agree.
I never meant to address anything else than that in issue #74 (i.e. IMHO #74 and #75 are duplicates; well never mind).

**Comment by mentaljam** [comment]
No, I will add a usage hint which will be shown to users on the first launch.

**Comment by Olf0** [comment]
A side note, as the conversation in #74 and #75 tended a little bit to a heated debate for me (and I surely contributed to that by not writing this earlier).
* I was addressing this purely from a users / user-experience perspective, i.e. only about "Look & Feel" / workflow for users.  Hence I deem it as irrelevant if something is technically an overlay or a Silica page for the issue description (but not for resolving it).
* I learnt from many software projects I was involved with (e.g. GPG4win, KDE's Kontact), that users want to use software on "idiot level": Things have to be absolutely obvious (otherwise they will be misinterpreted by some) and information has to be provided in the moment it is needed (otherwise it will be long forgotten, when needed).  And most importantly: Any additional step or window should be avoided, if not absolutely necessary (e.g. for new functionality).
I also became aware that this is, what I want, too.  So this is only about "ease of use", not about a lack of experience or intellect of some users.

**Comment by direc85** [comment]
I just now tested it and found that I have to click the rating stars in the application page in order to rate it. There is no indication that the element is clickable.

**Comment by mentaljam** [comment]
@direc85 But a hint is shown on the first launch.

**Comment by Pohli** [comment]
@mentaljam: Now direc85 experienced exactly what Olf0 stated in the second point of his last reply. Don't you see that?
